/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CurrentUser { 'principal' : Principal, 'role' : UserRole }
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Medication {
  'duration' : string,
  'dose' : string,
  'name' : string,
  'instructions' : string,
  'frequency' : string,
}
export interface Patient {
  'id' : bigint,
  'weight' : [] | [number],
  'height' : [] | [number],
  'nameBn' : [] | [string],
  'dateOfBirth' : [] | [Time],
  'createdAt' : Time,
  'fullName' : string,
  'email' : [] | [string],
  'pastSurgicalHistory' : [] | [string],
  'bloodGroup' : [] | [string],
  'address' : [] | [string],
  'gender' : Gender,
  'patientType' : PatientType,
  'chronicConditions' : Array<string>,
  'phone' : [] | [string],
  'allergies' : Array<string>,
}
export type PatientType = { 'admitted' : null } |
  { 'outdoor' : null };
export interface Prescription {
  'id' : bigint,
  'patientId' : bigint,
  'createdAt' : Time,
  'diagnosis' : [] | [string],
  'prescriptionDate' : Time,
  'medications' : Array<Medication>,
  'notes' : [] | [string],
  'visitId' : [] | [bigint],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : bigint,
  'vitalSigns' : VitalSigns,
  'patientId' : bigint,
  'createdAt' : Time,
  'visitDate' : Time,
  'visitType' : VisitType,
  'diagnosis' : [] | [string],
  'historyOfPresentIllness' : [] | [string],
  'notes' : [] | [string],
  'physicalExamination' : [] | [string],
  'chiefComplaint' : string,
}
export type VisitType = { 'admitted' : null } |
  { 'outdoor' : null };
export interface VitalSigns {
  'respiratoryRate' : [] | [string],
  'temperature' : [] | [string],
  'bloodPressure' : [] | [string],
  'oxygenSaturation' : [] | [string],
  'pulse' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPatient' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [Time],
      Gender,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      Array<string>,
      Array<string>,
      [] | [string],
      PatientType,
    ],
    Patient
  >,
  'createPrescription' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      Time,
      [] | [string],
      Array<Medication>,
      [] | [string],
    ],
    Prescription
  >,
  'createVisit' : ActorMethod<
    [
      bigint,
      Time,
      string,
      [] | [string],
      VitalSigns,
      [] | [string],
      [] | [string],
      [] | [string],
      VisitType,
    ],
    Visit
  >,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deletePrescription' : ActorMethod<[bigint], undefined>,
  'deleteVisit' : ActorMethod<[bigint], undefined>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<[], CurrentUser>,
  'getPatient' : ActorMethod<[bigint], [] | [Patient]>,
  'getPrescription' : ActorMethod<[bigint], [] | [Prescription]>,
  'getPrescriptionsByPatientId' : ActorMethod<[bigint], Array<Prescription>>,
  'getPrescriptionsByVisitId' : ActorMethod<[bigint], Array<Prescription>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisit' : ActorMethod<[bigint], [] | [Visit]>,
  'getVisitsByPatientId' : ActorMethod<[bigint], Array<Visit>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePatient' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [Time],
      Gender,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      Array<string>,
      Array<string>,
      [] | [string],
      PatientType,
    ],
    Patient
  >,
  'updatePrescription' : ActorMethod<
    [
      bigint,
      bigint,
      [] | [bigint],
      Time,
      [] | [string],
      Array<Medication>,
      [] | [string],
    ],
    Prescription
  >,
  'updateVisit' : ActorMethod<
    [
      bigint,
      bigint,
      Time,
      string,
      [] | [string],
      VitalSigns,
      [] | [string],
      [] | [string],
      [] | [string],
      VisitType,
    ],
    Visit
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];