/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientType = IDL.Variant({
  'admitted' : IDL.Null,
  'outdoor' : IDL.Null,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'nameBn' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Opt(Time),
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'pastSurgicalHistory' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'patientType' : PatientType,
  'chronicConditions' : IDL.Vec(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'allergies' : IDL.Vec(IDL.Text),
});
export const Medication = IDL.Record({
  'duration' : IDL.Text,
  'dose' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'frequency' : IDL.Text,
});
export const Prescription = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'diagnosis' : IDL.Opt(IDL.Text),
  'prescriptionDate' : Time,
  'medications' : IDL.Vec(Medication),
  'notes' : IDL.Opt(IDL.Text),
  'visitId' : IDL.Opt(IDL.Nat),
});
export const VitalSigns = IDL.Record({
  'respiratoryRate' : IDL.Opt(IDL.Text),
  'temperature' : IDL.Opt(IDL.Text),
  'bloodPressure' : IDL.Opt(IDL.Text),
  'oxygenSaturation' : IDL.Opt(IDL.Text),
  'pulse' : IDL.Opt(IDL.Text),
});
export const VisitType = IDL.Variant({
  'admitted' : IDL.Null,
  'outdoor' : IDL.Null,
});
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'vitalSigns' : VitalSigns,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'visitDate' : Time,
  'visitType' : VisitType,
  'diagnosis' : IDL.Opt(IDL.Text),
  'historyOfPresentIllness' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'physicalExamination' : IDL.Opt(IDL.Text),
  'chiefComplaint' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CurrentUser = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        Gender,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        PatientType,
      ],
      [Patient],
      [],
    ),
  'createPrescription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Time,
        IDL.Opt(IDL.Text),
        IDL.Vec(Medication),
        IDL.Opt(IDL.Text),
      ],
      [Prescription],
      [],
    ),
  'createVisit' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Opt(IDL.Text),
        VitalSigns,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        VisitType,
      ],
      [Visit],
      [],
    ),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'deletePrescription' : IDL.Func([IDL.Nat], [], []),
  'deleteVisit' : IDL.Func([IDL.Nat], [], []),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([], [CurrentUser], []),
  'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
  'getPrescription' : IDL.Func([IDL.Nat], [IDL.Opt(Prescription)], ['query']),
  'getPrescriptionsByPatientId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPrescriptionsByVisitId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
  'getVisitsByPatientId' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePatient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        Gender,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        PatientType,
      ],
      [Patient],
      [],
    ),
  'updatePrescription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Time,
        IDL.Opt(IDL.Text),
        IDL.Vec(Medication),
        IDL.Opt(IDL.Text),
      ],
      [Prescription],
      [],
    ),
  'updateVisit' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Opt(IDL.Text),
        VitalSigns,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        VisitType,
      ],
      [Visit],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientType = IDL.Variant({
    'admitted' : IDL.Null,
    'outdoor' : IDL.Null,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'nameBn' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Opt(Time),
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'pastSurgicalHistory' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'patientType' : PatientType,
    'chronicConditions' : IDL.Vec(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const Medication = IDL.Record({
    'duration' : IDL.Text,
    'dose' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'diagnosis' : IDL.Opt(IDL.Text),
    'prescriptionDate' : Time,
    'medications' : IDL.Vec(Medication),
    'notes' : IDL.Opt(IDL.Text),
    'visitId' : IDL.Opt(IDL.Nat),
  });
  const VitalSigns = IDL.Record({
    'respiratoryRate' : IDL.Opt(IDL.Text),
    'temperature' : IDL.Opt(IDL.Text),
    'bloodPressure' : IDL.Opt(IDL.Text),
    'oxygenSaturation' : IDL.Opt(IDL.Text),
    'pulse' : IDL.Opt(IDL.Text),
  });
  const VisitType = IDL.Variant({
    'admitted' : IDL.Null,
    'outdoor' : IDL.Null,
  });
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'vitalSigns' : VitalSigns,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'visitDate' : Time,
    'visitType' : VisitType,
    'diagnosis' : IDL.Opt(IDL.Text),
    'historyOfPresentIllness' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'physicalExamination' : IDL.Opt(IDL.Text),
    'chiefComplaint' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CurrentUser = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          Gender,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          PatientType,
        ],
        [Patient],
        [],
      ),
    'createPrescription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Time,
          IDL.Opt(IDL.Text),
          IDL.Vec(Medication),
          IDL.Opt(IDL.Text),
        ],
        [Prescription],
        [],
      ),
    'createVisit' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Text),
          VitalSigns,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          VisitType,
        ],
        [Visit],
        [],
      ),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'deletePrescription' : IDL.Func([IDL.Nat], [], []),
    'deleteVisit' : IDL.Func([IDL.Nat], [], []),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([], [CurrentUser], []),
    'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
    'getPrescription' : IDL.Func([IDL.Nat], [IDL.Opt(Prescription)], ['query']),
    'getPrescriptionsByPatientId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPrescriptionsByVisitId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
    'getVisitsByPatientId' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePatient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          Gender,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          PatientType,
        ],
        [Patient],
        [],
      ),
    'updatePrescription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Time,
          IDL.Opt(IDL.Text),
          IDL.Vec(Medication),
          IDL.Opt(IDL.Text),
        ],
        [Prescription],
        [],
      ),
    'updateVisit' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Text),
          VitalSigns,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          VisitType,
        ],
        [Visit],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };