/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Medication {
    duration: string;
    dose: string;
    name: string;
    instructions: string;
    frequency: string;
}
export interface CurrentUser {
    principal: Principal;
    role: UserRole;
}
export type Time = bigint;
export interface VitalSigns {
    respiratoryRate?: string;
    temperature?: string;
    bloodPressure?: string;
    oxygenSaturation?: string;
    pulse?: string;
}
export interface Prescription {
    id: bigint;
    patientId: bigint;
    createdAt: Time;
    diagnosis?: string;
    prescriptionDate: Time;
    medications: Array<Medication>;
    notes?: string;
    visitId?: bigint;
}
export interface Visit {
    id: bigint;
    vitalSigns: VitalSigns;
    patientId: bigint;
    createdAt: Time;
    visitDate: Time;
    visitType: VisitType;
    diagnosis?: string;
    historyOfPresentIllness?: string;
    notes?: string;
    physicalExamination?: string;
    chiefComplaint: string;
}
export interface UserProfile {
    name: string;
}
export interface Patient {
    id: bigint;
    weight?: number;
    height?: number;
    nameBn?: string;
    dateOfBirth?: Time;
    createdAt: Time;
    fullName: string;
    email?: string;
    pastSurgicalHistory?: string;
    bloodGroup?: string;
    address?: string;
    gender: Gender;
    patientType: PatientType;
    chronicConditions: Array<string>;
    phone?: string;
    allergies: Array<string>;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VisitType {
    admitted = "admitted",
    outdoor = "outdoor"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPatient(fullName: string, nameBn: string | null, dateOfBirth: Time | null, gender: Gender, phone: string | null, email: string | null, address: string | null, bloodGroup: string | null, weight: number | null, height: number | null, allergies: Array<string>, chronicConditions: Array<string>, pastSurgicalHistory: string | null, patientType: PatientType): Promise<Patient>;
    createPrescription(patientId: bigint, visitId: bigint | null, prescriptionDate: Time, diagnosis: string | null, medications: Array<Medication>, notes: string | null): Promise<Prescription>;
    createVisit(patientId: bigint, visitDate: Time, chiefComplaint: string, historyOfPresentIllness: string | null, vitalSigns: VitalSigns, physicalExamination: string | null, diagnosis: string | null, notes: string | null, visitType: VisitType): Promise<Visit>;
    deletePatient(id: bigint): Promise<void>;
    deletePrescription(id: bigint): Promise<void>;
    deleteVisit(id: bigint): Promise<void>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllPrescriptions(): Promise<Array<Prescription>>;
    getAllVisits(): Promise<Array<Visit>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUser(): Promise<CurrentUser>;
    getPatient(id: bigint): Promise<Patient | null>;
    getPrescription(id: bigint): Promise<Prescription | null>;
    getPrescriptionsByPatientId(patientId: bigint): Promise<Array<Prescription>>;
    getPrescriptionsByVisitId(visitId: bigint): Promise<Array<Prescription>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisit(id: bigint): Promise<Visit | null>;
    getVisitsByPatientId(patientId: bigint): Promise<Array<Visit>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePatient(id: bigint, fullName: string, nameBn: string | null, dateOfBirth: Time | null, gender: Gender, phone: string | null, email: string | null, address: string | null, bloodGroup: string | null, weight: number | null, height: number | null, allergies: Array<string>, chronicConditions: Array<string>, pastSurgicalHistory: string | null, patientType: PatientType): Promise<Patient>;
    updatePrescription(id: bigint, patientId: bigint, visitId: bigint | null, prescriptionDate: Time, diagnosis: string | null, medications: Array<Medication>, notes: string | null): Promise<Prescription>;
    updateVisit(id: bigint, patientId: bigint, visitDate: Time, chiefComplaint: string, historyOfPresentIllness: string | null, vitalSigns: VitalSigns, physicalExamination: string | null, diagnosis: string | null, notes: string | null, visitType: VisitType): Promise<Visit>;
}
import type { CurrentUser as _CurrentUser, Gender as _Gender, Medication as _Medication, Patient as _Patient, PatientType as _PatientType, Prescription as _Prescription, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Visit as _Visit, VisitType as _VisitType, VitalSigns as _VitalSigns } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPatient(arg0: string, arg1: string | null, arg2: Time | null, arg3: Gender, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: number | null, arg9: number | null, arg10: Array<string>, arg11: Array<string>, arg12: string | null, arg13: PatientType): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), arg10, arg11, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg12), to_candid_PatientType_n8(this._uploadFile, this._downloadFile, arg13));
                return from_candid_Patient_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), arg10, arg11, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg12), to_candid_PatientType_n8(this._uploadFile, this._downloadFile, arg13));
            return from_candid_Patient_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPrescription(arg0: bigint, arg1: bigint | null, arg2: Time, arg3: string | null, arg4: Array<Medication>, arg5: string | null): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Prescription_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Prescription_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVisit(arg0: bigint, arg1: Time, arg2: string, arg3: string | null, arg4: VitalSigns, arg5: string | null, arg6: string | null, arg7: string | null, arg8: VisitType): Promise<Visit> {
        if (this.processError) {
            try {
                const result = await this.actor.createVisit(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_VitalSigns_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_VisitType_n25(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Visit_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVisit(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_VitalSigns_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_VisitType_n25(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Visit_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePatient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePrescription(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrescription(arg0);
            return result;
        }
    }
    async deleteVisit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisit(arg0);
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrescriptions(): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrescriptions();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrescriptions();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVisits(): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisits();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisits();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<CurrentUser> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_CurrentUser_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_CurrentUser_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: bigint): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescription(arg0: bigint): Promise<Prescription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescription(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescription(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionsByPatientId(arg0: bigint): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByPatientId(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByPatientId(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionsByVisitId(arg0: bigint): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByVisitId(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByVisitId(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisit(arg0: bigint): Promise<Visit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisit(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisit(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitsByPatientId(arg0: bigint): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitsByPatientId(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitsByPatientId(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: string, arg2: string | null, arg3: Time | null, arg4: Gender, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: number | null, arg10: number | null, arg11: Array<string>, arg12: Array<string>, arg13: string | null, arg14: PatientType): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_Gender_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg13), to_candid_PatientType_n8(this._uploadFile, this._downloadFile, arg14));
                return from_candid_Patient_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_Gender_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg13), to_candid_PatientType_n8(this._uploadFile, this._downloadFile, arg14));
            return from_candid_Patient_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePrescription(arg0: bigint, arg1: bigint, arg2: bigint | null, arg3: Time, arg4: string | null, arg5: Array<Medication>, arg6: string | null): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescription(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Prescription_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescription(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Prescription_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVisit(arg0: bigint, arg1: bigint, arg2: Time, arg3: string, arg4: string | null, arg5: VitalSigns, arg6: string | null, arg7: string | null, arg8: string | null, arg9: VisitType): Promise<Visit> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisit(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_VitalSigns_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), to_candid_VisitType_n25(this._uploadFile, this._downloadFile, arg9));
                return from_candid_Visit_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisit(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_VitalSigns_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), to_candid_VisitType_n25(this._uploadFile, this._downloadFile, arg9));
            return from_candid_Visit_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CurrentUser_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentUser): CurrentUser {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PatientType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientType): PatientType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Prescription_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prescription): Prescription {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_VisitType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitType): VisitType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Visit_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visit): Visit {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_VitalSigns_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VitalSigns): VitalSigns {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Prescription | null {
    return value.length === 0 ? null : from_candid_Prescription_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Visit]): Visit | null {
    return value.length === 0 ? null : from_candid_Visit_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: [] | [number];
    height: [] | [number];
    nameBn: [] | [string];
    dateOfBirth: [] | [_Time];
    createdAt: _Time;
    fullName: string;
    email: [] | [string];
    pastSurgicalHistory: [] | [string];
    bloodGroup: [] | [string];
    address: [] | [string];
    gender: _Gender;
    patientType: _PatientType;
    chronicConditions: Array<string>;
    phone: [] | [string];
    allergies: Array<string>;
}): {
    id: bigint;
    weight?: number;
    height?: number;
    nameBn?: string;
    dateOfBirth?: Time;
    createdAt: Time;
    fullName: string;
    email?: string;
    pastSurgicalHistory?: string;
    bloodGroup?: string;
    address?: string;
    gender: Gender;
    patientType: PatientType;
    chronicConditions: Array<string>;
    phone?: string;
    allergies: Array<string>;
} {
    return {
        id: value.id,
        weight: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.weight)),
        height: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.height)),
        nameBn: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.nameBn)),
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.dateOfBirth)),
        createdAt: value.createdAt,
        fullName: value.fullName,
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        pastSurgicalHistory: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.pastSurgicalHistory)),
        bloodGroup: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.bloodGroup)),
        address: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.address)),
        gender: from_candid_Gender_n15(_uploadFile, _downloadFile, value.gender),
        patientType: from_candid_PatientType_n17(_uploadFile, _downloadFile, value.patientType),
        chronicConditions: value.chronicConditions,
        phone: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.phone)),
        allergies: value.allergies
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    patientId: bigint;
    createdAt: _Time;
    diagnosis: [] | [string];
    prescriptionDate: _Time;
    medications: Array<_Medication>;
    notes: [] | [string];
    visitId: [] | [bigint];
}): {
    id: bigint;
    patientId: bigint;
    createdAt: Time;
    diagnosis?: string;
    prescriptionDate: Time;
    medications: Array<Medication>;
    notes?: string;
    visitId?: bigint;
} {
    return {
        id: value.id,
        patientId: value.patientId,
        createdAt: value.createdAt,
        diagnosis: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.diagnosis)),
        prescriptionDate: value.prescriptionDate,
        medications: value.medications,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        visitId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.visitId))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    vitalSigns: _VitalSigns;
    patientId: bigint;
    createdAt: _Time;
    visitDate: _Time;
    visitType: _VisitType;
    diagnosis: [] | [string];
    historyOfPresentIllness: [] | [string];
    notes: [] | [string];
    physicalExamination: [] | [string];
    chiefComplaint: string;
}): {
    id: bigint;
    vitalSigns: VitalSigns;
    patientId: bigint;
    createdAt: Time;
    visitDate: Time;
    visitType: VisitType;
    diagnosis?: string;
    historyOfPresentIllness?: string;
    notes?: string;
    physicalExamination?: string;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        vitalSigns: from_candid_VitalSigns_n28(_uploadFile, _downloadFile, value.vitalSigns),
        patientId: value.patientId,
        createdAt: value.createdAt,
        visitDate: value.visitDate,
        visitType: from_candid_VisitType_n30(_uploadFile, _downloadFile, value.visitType),
        diagnosis: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.diagnosis)),
        historyOfPresentIllness: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.historyOfPresentIllness)),
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        physicalExamination: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.physicalExamination)),
        chiefComplaint: value.chiefComplaint
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    respiratoryRate: [] | [string];
    temperature: [] | [string];
    bloodPressure: [] | [string];
    oxygenSaturation: [] | [string];
    pulse: [] | [string];
}): {
    respiratoryRate?: string;
    temperature?: string;
    bloodPressure?: string;
    oxygenSaturation?: string;
    pulse?: string;
} {
    return {
        respiratoryRate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.respiratoryRate)),
        temperature: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.temperature)),
        bloodPressure: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.bloodPressure)),
        oxygenSaturation: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.oxygenSaturation)),
        pulse: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.pulse))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n35(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admitted: null;
} | {
    outdoor: null;
}): VisitType {
    return "admitted" in value ? VisitType.admitted : "outdoor" in value ? VisitType.outdoor : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prescription>): Array<Prescription> {
    return value.map((x)=>from_candid_Prescription_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visit>): Array<Visit> {
    return value.map((x)=>from_candid_Visit_n26(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PatientType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientType): _PatientType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VisitType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitType): _VisitType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VitalSigns_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VitalSigns): _VitalSigns {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    respiratoryRate?: string;
    temperature?: string;
    bloodPressure?: string;
    oxygenSaturation?: string;
    pulse?: string;
}): {
    respiratoryRate: [] | [string];
    temperature: [] | [string];
    bloodPressure: [] | [string];
    oxygenSaturation: [] | [string];
    pulse: [] | [string];
} {
    return {
        respiratoryRate: value.respiratoryRate ? candid_some(value.respiratoryRate) : candid_none(),
        temperature: value.temperature ? candid_some(value.temperature) : candid_none(),
        bloodPressure: value.bloodPressure ? candid_some(value.bloodPressure) : candid_none(),
        oxygenSaturation: value.oxygenSaturation ? candid_some(value.oxygenSaturation) : candid_none(),
        pulse: value.pulse ? candid_some(value.pulse) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitType): {
    admitted: null;
} | {
    outdoor: null;
} {
    return value == VisitType.admitted ? {
        admitted: null
    } : value == VisitType.outdoor ? {
        outdoor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
